/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicDownloadProjectZipRouteImport } from './routes/api/public/download-project-zip'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDownloadProjectZipRoute =
  ApiPublicDownloadProjectZipRouteImport.update({
    id: '/api/public/download-project-zip',
    path: '/api/public/download-project-zip',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/download-project-zip': typeof ApiPublicDownloadProjectZipRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/download-project-zip': typeof ApiPublicDownloadProjectZipRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/download-project-zip': typeof ApiPublicDownloadProjectZipRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/public/download-project-zip'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/download-project-zip'
  id: '__root__' | '/' | '/api/public/download-project-zip'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicDownloadProjectZipRoute: typeof ApiPublicDownloadProjectZipRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/download-project-zip': {
      id: '/api/public/download-project-zip'
      path: '/api/public/download-project-zip'
      fullPath: '/api/public/download-project-zip'
      preLoaderRoute: typeof ApiPublicDownloadProjectZipRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicDownloadProjectZipRoute: ApiPublicDownloadProjectZipRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
